### ISSUE TITLE
Run NocTestAXI403 Fail

### ISSUE THREAD

**Issue by Alan-19950616** [ucb-bar/constellation#35]
# Command

> CONSTELLATION_STANDALONE=1 sbt "testOnly constellation.NoCTestAXI403"

# Error Info

```
Constellation: AXI4NoC Starting NoC RTL generation
Constellation: AXI4NoC Finished NoC RTL generation
[info] constellation.NoCTestAXI403 *** ABORTED ***
[info]   java.lang.OutOfMemoryError: GC overhead limit exceeded
[info]   at scala.LowPriorityImplicits.wrapRefArray(Predef.scala:614)
[info]   at firrtl.ir.Block.mapStmt(IR.scala:653)
[info]   at firrtl.Mappers$StmtMagnet$$anon$3.map(Mappers.scala:31)
[info]   at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:48)
[info]   at firrtl.passes.TrimIntervals.alignStmtBP(TrimIntervals.scala:67)
[info]   at firrtl.passes.TrimIntervals.$anonfun$alignModuleBP$1(TrimIntervals.scala:54)
[info]   at firrtl.passes.TrimIntervals$$Lambda$4922/1738622642.apply(Unknown Source)
[info]   at firrtl.ir.Module.mapStmt(IR.scala:1198)
[info]   at firrtl.Mappers$ModuleMagnet$$anon$14.map(Mappers.scala:108)
[info]   at firrtl.Mappers$ModuleMap$.map$extension(Mappers.scala:121)
[info]   ...
[error] Uncaught exception when running constellation.NoCTestAXI403: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] sbt.ForkMain$ForkError: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] 	at scala.LowPriorityImplicits.wrapRefArray(Predef.scala:614)
[error] 	at firrtl.ir.Block.mapStmt(IR.scala:653)
[error] 	at firrtl.Mappers$StmtMagnet$$anon$3.map(Mappers.scala:31)
[error] 	at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:48)
[error] 	at firrtl.passes.TrimIntervals.alignStmtBP(TrimIntervals.scala:67)
[error] 	at firrtl.passes.TrimIntervals.$anonfun$alignModuleBP$1(TrimIntervals.scala:54)
[error] 	at firrtl.passes.TrimIntervals$$Lambda$4922/1738622642.apply(Unknown Source)
[error] 	at firrtl.ir.Module.mapStmt(IR.scala:1198)
[error] 	at firrtl.Mappers$ModuleMagnet$$anon$14.map(Mappers.scala:108)
[error] 	at firrtl.Mappers$ModuleMap$.map$extension(Mappers.scala:121)
[error] 	at firrtl.passes.TrimIntervals.alignModuleBP(TrimIntervals.scala:54)
[error] 	at firrtl.passes.TrimIntervals.$anonfun$run$3(TrimIntervals.scala:36)
[error] 	at firrtl.passes.TrimIntervals$$Lambda$4920/737069963.apply(Unknown Source)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
[error] 	at scala.collection.TraversableLike$$Lambda$63/1484594489.apply(Unknown Source)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:285)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at firrtl.ir.Circuit.mapModule(IR.scala:1235)
[error] 	at firrtl.Mappers$CircuitMagnet$$anon$18.map(Mappers.scala:130)
[error] 	at firrtl.Mappers$CircuitMap$.map$extension(Mappers.scala:140)
[error] 	at firrtl.passes.TrimIntervals.run(TrimIntervals.scala:36)
[error] 	at firrtl.passes.Pass.execute(Pass.scala:14)
[error] 	at firrtl.passes.Pass.execute$(Pass.scala:14)
[error] 	at firrtl.passes.TrimIntervals.execute(TrimIntervals.scala:23)
[error] 	at firrtl.Transform.transform(Compiler.scala:280)
[error] 	at firrtl.Transform.transform$(Compiler.scala:280)
[error] 	at firrtl.passes.TrimIntervals.transform(TrimIntervals.scala:23)
[error] 	at firrtl.stage.transforms.ExpandPrepares.execute(ExpandPrepares.scala:19)
[info] Run completed in 2 minutes, 52 seconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 1
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error during tests:
[error] 	constellation.NoCTestAXI403
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 179 s (02:59), completed Jan 18, 2023 2:57:25 PM
```

**Comment by jerryz123** [comment]
Thanks for the report. I'll check on this

**Comment by Alan-19950616** [comment]
> Thanks for the report. I'll check on this

@jerryz123 How is it going?

**Comment by jerryz123** [comment]
Currently working on similar issues, bumping to latest version of Chisel

**Comment by jerryz123** [comment]
Try setting the environment variable:
```JAVA_TOOL_OPTIONS=-Xmx8G```

**Comment by Alan-19950616** [comment]
I tried to increase **-Xmx** and **-Xss** in  **.github/workflows/ci.yml**. I got the same error message as before. @jerryz123

**Comment by jerryz123** [comment]
If you are running this locally, you have to set the JAVA_TOOL_OPTIONS environment variable like the way CI sets it.

**Comment by Alan-19950616** [comment]
thanks for your reply. 
This seems to be working, but there are new mistakes.
**sbt.ForkMain 32891 failed with exit code 137**
![image](https://user-images.githubusercontent.com/46317534/217163623-0cb7374d-bee3-49e8-bf64-f85c6eb2aa44.png)

**Comment by Alan-19950616** [comment]
@jerryz123

**Comment by jerryz123** [comment]
Can you try the current version of Constellation?
