### ISSUE TITLE
Run Minimal-Standalone Testing Fail

### ISSUE THREAD

**Issue by CathyGong516** [ucb-bar/constellation#38]
### Commend
`CONSTELLATION_STANDALONE=1 sbt "testOnly constellation.NoCTest00"`
### Describe
When I trying to run **Minimal-Standalone Testing**, it failed when enter line`CONSTELLATION_STANDALONE=1 sbt "testOnly constellation.NoCTest00` I want to ask for some help.
### Error Info
```
[error] sbt.librarymanagement.ResolveException: Error downloading edu.berkeley.cs:api-config-chipsalliance_2.12:1.2-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/local/edu.berkeley.cs/api-config-chipsalliance_2.12/1.2-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/api-config-chipsalliance_2.12/1.2-SNAPSHOT/api-config-chipsalliance_2.12-1.2-SNAPSHOT.pom
[error] Error downloading edu.berkeley.cs:rocketchip_2.12:1.2-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/local/edu.berkeley.cs/rocketchip_2.12/1.2-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/rocketchip_2.12/1.2-SNAPSHOT/rocketchip_2.12-1.2-SNAPSHOT.pom
[error] Error downloading edu.berkeley.cs:rocket-macros_2.12:1.2-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/local/edu.berkeley.cs/rocket-macros_2.12/1.2-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/rocket-macros_2.12/1.2-SNAPSHOT/rocket-macros_2.12-1.2-SNAPSHOT.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3525)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading edu.berkeley.cs:api-config-chipsalliance_2.12:1.2-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/local/edu.berkeley.cs/api-config-chipsalliance_2.12/1.2-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/api-config-chipsalliance_2.12/1.2-SNAPSHOT/api-config-chipsalliance_2.12-1.2-SNAPSHOT.pom
[error] Error downloading edu.berkeley.cs:rocketchip_2.12:1.2-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/local/edu.berkeley.cs/rocketchip_2.12/1.2-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/rocketchip_2.12/1.2-SNAPSHOT/rocketchip_2.12-1.2-SNAPSHOT.pom
[error] Error downloading edu.berkeley.cs:rocket-macros_2.12:1.2-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/local/edu.berkeley.cs/rocket-macros_2.12/1.2-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/rocket-macros_2.12/1.2-SNAPSHOT/rocket-macros_2.12-1.2-SNAPSHOT.pom
[error] Total time: 3 s, completed Feb 8, 2023, 11:59:04 AM
```

**Comment by jerryz123** [comment]
Can you specify what commit of constellation you are using?

**Comment by CathyGong516** [comment]
In this website [https://github.com/ucb-bar/constellation/blob/master/docs/source/Introduction/SimpleTests.rst](url) I'm not sure is this the answer you want?

**Comment by jerryz123** [comment]
Can you tell me what the result of running `git log -1` in the constellation repository prints?

**Comment by CathyGong516** [comment]
`commit 161a5bc9edca3e7ac59f09d31d306918b3a2ce55 (HEAD -> master, origin/master, origin/HEAD)
Author: Jerry Zhao <jerryz123@berkeley.edu>
Date:   Wed Jan 4 01:18:16 2023 -0800

    Fix AXI4 connect syntax`

**Comment by jerryz123** [comment]
Can you pull the latest master again? And try again?

In constellation, run `git fetch && git pull origin master`

Then run these commands (from the instructions)
```
git clone https://github.com/chipsalliance/rocket-chip.git
cd rocket-chip
git checkout 3b5fb3c043ccc2cea81ed7a44b295f4652d0ba02
git submodule update --init --recursive
sbt "publishLocal"
sbt "project api-config-chipsalliance; set publishArtifact := true; publishLocal"
sbt "project rocket-macros; set publishArtifact := true; publishLocal"
sbt "project hardfloat; set publishArtifact := true; publishLocal"
```

**Comment by CathyGong516** [comment]
The internet is a bit slow right now，it may take long time to build, probably because of the region, I'll try and get back to you later, thank you for your patience.

**Comment by CathyGong516** [comment]
Thanks for your help, I had already run this section, best wishes to you~
