### ISSUE TITLE
about Minimal-Standalone Testing

### ISSUE THREAD

**Issue by beiming0110** [ucb-bar/constellation#67]
follow the Documentation: http://constellation.readthedocs.io/
install Espresso
and input those commind :

1. cd constellation
2. CONSTELLATION_STANDALONE=1 sbt "testOnly constellation.NoCTest00"

terminal report error:

$ CONSTELLATION_STANDALONE=1 sbt "testOnly constellation.NoCTest00"
[info] welcome to sbt 1.4.9 (Oracle Corporation Java 1.8.0_25)
[info] loading project definition from /home/wpc/NOC_gen/constellation/project
[info] loading settings for project constellation from build.sbt ...
[info] set current project to constellation (in build file:/home/wpc/NOC_gen/constellation/)
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading edu.berkeley.cs:cde_2.13:1.6.0
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/localedu.berkeley.cs/cde_2.13/1.6.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/cde_2.13/1.6.0/cde_2.13-1.6.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/edu/berkeley/cs/cde_2.13/1.6.0/cde_2.13-1.6.0.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/maven-snapshots/edu/berkeley/cs/cde_2.13/1.6.0/cde_2.13-1.6.0.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.typesafe.com/typesafe/ivy-releases/edu.berkeley.cs/cde_2.13/1.6.0/ivys/ivy.xm

How to solve this problem？help me !

**Comment by jerryz123** [comment]
Minimal standalone testing is currently broken, I recommend trying to follow the documentation for running it within Chipyard. 

All minimal standalone testing js supported in Chipyard as well

**Comment by beiming0110** [comment]
> Minimal standalone testing is currently broken, I recommend trying to follow the documentation for running it within Chipyard.
> 
> All minimal standalone testing js supported in Chipyard as well

I meet the same issue within Chipyard

**Comment by beiming0110** [comment]
> Minimal standalone testing is currently broken, I recommend trying to follow the documentation for running it within Chipyard.
> 
> All minimal standalone testing js supported in Chipyard as well

I meet the same issue within Chipyard

**Comment by jerryz123** [comment]
Can you paste the error in Chipyard's setup that you experienced?

**Comment by beiming0110** [comment]
> Can you paste the error in Chipyard's setup that you experienced?

Chipyard ：1.8.0
conda:         24.1.2

command: 
cd chipyard/sims/vcs
make 

$ make 
Running with RISCV=/home/wpc/riscv/riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14
mkdir -p /home/wpc/NOC_gen/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig
cd /home/wpc/NOC_gen/chipyard && sbt  ";project chipyard; runMain chipyard.Generator  --target-dir /home/wpc/NOC_gen/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig --name chipyard.TestHarness.RocketConfig --top-module chipyard.TestHarness --legacy-configs chipyard:RocketConfig "
Picked up JAVA_TOOL_OPTIONS: -Xmx8G -Xss8M -Djava.io.tmpdir=/home/wpc/NOC_gen/chipyard/.java_tmp
[info] welcome to sbt 1.8.2 (Oracle Corporation Java 1.8.0_25)
[info] loading project definition from /home/wpc/NOC_gen/chipyard/project/project
[info] loading settings for project chipyard-build from plugins.sbt ...
[info] loading project definition from /home/wpc/NOC_gen/chipyard/project
[info] loading settings for project chipyardRoot from build.sbt ...
[info] loading settings for project hardfloat from build.sbt ...
[info] loading settings for project rocketConfig from build.sbt ...
[info] loading settings for project testchipip from build.sbt ...
[info] loading settings for project constellation from build.sbt ...
[info] loading settings for project icenet from build.sbt ...
[info] loading settings for project hwacha from build.sbt ...
[info] loading settings for project boom from build.sbt ...
[info] loading settings for project cva6 from build.sbt ...
[info] loading settings for project ibex from build.sbt ...
[info] loading settings for project sodor from build.sbt ...
[info] loading settings for project gemmini from build.sbt ...
[info] loading settings for project tapeout from build.sbt ...
[info] loading settings for project sim-build from plugins.sbt ...
[info] loading project definition from /home/wpc/NOC_gen/chipyard/sims/firesim/sim/project
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.sbt:sbt-ghpages:0.6.3 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 		com.eed3si9n:sbt-unidoc:0.4.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 		com.typesafe.sbt:sbt-site:1.3.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-ghpages;sbtVersion=1.0;scalaVersion=2.12:0.6.3
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/localcom.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.3/sbt-ghpages-0.6.3.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.3/sbt-ghpages-0.6.3.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.3/sbt-ghpages-0.6.3.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-ghpages/0.6.3/ivys/ivy.xml
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.typesafe.sbt/sbt-ghpages/0.6.3/ivys/ivy.xml
[error] Error downloading com.eed3si9n:sbt-unidoc;sbtVersion=1.0;scalaVersion=2.12:0.4.1
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/localcom.eed3si9n/sbt-unidoc/scala_2.12/sbt_1.0/0.4.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-unidoc/0.4.1/ivys/ivy.xml
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.eed3si9n/sbt-unidoc/0.4.1/ivys/ivy.xml
[error] Error downloading com.typesafe.sbt:sbt-site;sbtVersion=1.0;scalaVersion=2.12:1.3.1
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/localcom.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.3.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-site_2.12_1.0/1.3.1/sbt-site-1.3.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-site_2.12_1.0/1.3.1/sbt-site-1.3.1.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-site_2.12_1.0/1.3.1/sbt-site-1.3.1.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-site/1.3.1/ivys/ivy.xml
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.typesafe.sbt/sbt-site/1.3.1/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at lmcoursier.CoursierDependencyResolution$$Lambda$4145/136794968.apply(Unknown Source)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$3067/874281428.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.util.Tracked$$$Lambda$3030/397940575.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$3069/176909373.apply(Unknown Source)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$3063/776856287.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.util.Tracked$$$Lambda$2883/55941687.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
[error] 	at sbt.Classpaths$$$Lambda$582/1585821446.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at scala.Function1$$Lambda$324/419775592.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$2660/2086945474.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.Execute$$Lambda$2689/1614212607.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.Execute$$Lambda$2673/1934729582.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2687/796774130.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-ghpages;sbtVersion=1.0;scalaVersion=2.12:0.6.
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/localcom.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.3/sbt-ghpages-0.6.3.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.3/sbt-ghpages-0.6.3.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.3/sbt-ghpages-0.6.3.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-ghpages/0.6.3/ivys/ivy.xml
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.typesafe.sbt/sbt-ghpages/0.6.3/ivys/ivy.xml
[error] Error downloading com.eed3si9n:sbt-unidoc;sbtVersion=1.0;scalaVersion=2.12:0.4.1
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/localcom.eed3si9n/sbt-unidoc/scala_2.12/sbt_1.0/0.4.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-unidoc/0.4.1/ivys/ivy.xml
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.eed3si9n/sbt-unidoc/0.4.1/ivys/ivy.xml
[error] Error downloading com.typesafe.sbt:sbt-site;sbtVersion=1.0;scalaVersion=2.12:1.3.1
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/localcom.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.3.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-site_2.12_1.0/1.3.1/sbt-site-1.3.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-site_2.12_1.0/1.3.1/sbt-site-1.3.1.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-site_2.12_1.0/1.3.1/sbt-site-1.3.1.pom
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-site/1.3.1/ivys/ivy.xml
[error]   download error: Caught javax.net.ssl.SSLHandshakeException (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.typesafe.sbt/sbt-site/1.3.1/ivys/ivy.xml
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)


Seems to be a dependency download failure for sbt.

**Comment by jerryz123** [comment]
You are right, it seems like SBT is failing to download some dependency.
You can try cloning from a different machine, but this seems to be caused by something unusual in your network.

**Comment by beiming0110** [comment]
> You are right, it seems like SBT is failing to download some dependency. You can try cloning from a different machine, but this seems to be caused by something unusual in your network.

Thank you for your resbonse.
I tried it on a different machine ,but report new error:

cd chipyard/sims/vcs
make 

Running with RISCV=/home/wpc/riscv-gnu-toolchain
mkdir -p /home/wpc/NOC/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig
cd /home/wpc/NOC/chipyard && sbt  ";project chipyard; runMain chipyard.Generator  --target-dir /home/wpc/NOC/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig --name chipyard.TestHarness.RocketConfig --top-module chipyard.TestHarness --legacy-configs chipyard:RocketConfig "
Picked up JAVA_TOOL_OPTIONS: -Xmx8G -Xss8M -Djava.io.tmpdir=/home/wpc/NOC/chipyard/.java_tmp
Picked up JAVA_TOOL_OPTIONS: -Xmx8G -Xss8M -Djava.io.tmpdir=/home/wpc/NOC/chipyard/.java_tmp
[info] welcome to sbt 1.8.2 (Ubuntu Java 11.0.22)
[info] loading project definition from /home/wpc/NOC/chipyard/project/project
[info] loading settings for project chipyard-build from plugins.sbt ...
[info] loading project definition from /home/wpc/NOC/chipyard/project
[info] loading settings for project chipyardRoot from build.sbt ...
[info] loading settings for project hardfloat from build.sbt ...
[info] loading settings for project rocketConfig from build.sbt ...
[info] loading settings for project testchipip from build.sbt ...
[info] loading settings for project constellation from build.sbt ...
[info] loading settings for project icenet from build.sbt ...
[info] loading settings for project hwacha from build.sbt ...
[info] loading settings for project boom from build.sbt ...
[info] loading settings for project cva6 from build.sbt ...
[info] loading settings for project ibex from build.sbt ...
[info] loading settings for project sodor from build.sbt ...
[info] loading settings for project gemmini from build.sbt ...
[info] loading settings for project tapeout from build.sbt ...
[info] loading settings for project sim-build from plugins.sbt ...
[info] loading project definition from /home/wpc/NOC/chipyard/sims/firesim/sim/project
[info] loading settings for project firesim from build.sbt ...
[info] loading settings for project targetutils from build.sbt ...
[info] loading settings for project midas from build.sbt ...
java.lang.RuntimeException: No project 'rocketchip_blocks' in 'file:/home/wpc/NOC/chipyard/'.
Valid project IDs: api-config-chipsalliance, boom, chipyard, chipyardRoot, constellation, cva6, dsptools, fft_generator, firechip, fpga_platforms, fpga_shells, gemmini, hardfloat, hwacha, ibex, icenet, iocell, nvdla, rocket-dsp-utils, rocketConfig, rocketMacros, rocketchip, sha3, sifive_blocks, sifive_cache, sodor, tapeout, testchipip, tracegen
	at scala.sys.package$.error(package.scala:30)
	at sbt.internal.Load$.$anonfun$checkAll$3(Load.scala:614)
	at sbt.internal.Load$.$anonfun$checkAll$3$adapted(Load.scala:608)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at sbt.internal.Load$.$anonfun$checkAll$2(Load.scala:608)
	at sbt.internal.Load$.$anonfun$checkAll$2$adapted(Load.scala:608)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:273)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
	at sbt.internal.Load$.checkAll(Load.scala:608)
	at sbt.internal.Load$.loadURI(Load.scala:501)
	at sbt.internal.Load$.load(Load.scala:479)
	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:241)
	at sbt.internal.Load$.timed(Load.scala:1406)
	at sbt.internal.Load$.apply(Load.scala:241)
	at sbt.internal.Load$.defaultLoad(Load.scala:56)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:961)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:961)
	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:914)
	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:245)
	at sbt.MainLoop$.processCommand(MainLoop.scala:278)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:163)
	at sbt.MainLoop$.run(MainLoop.scala:144)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
	at sbt.StandardMain$.runManaged(Main.scala:223)
	at sbt.xMain$.$anonfun$run$11(Main.scala:133)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:578)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:358)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:568)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:568)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:358)
	at sbt.xMain$.withStreams$1(Main.scala:87)
	at sbt.xMain$.run(Main.scala:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:120)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
[error] No project 'rocketchip_blocks' in 'file:/home/wpc/NOC/chipyard/'.
[error] Valid project IDs: api-config-chipsalliance, boom, chipyard, chipyardRoot, constellation, cva6, dsptools, fft_generator, firechip, fpga_platforms, fpga_shells, gemmini, hardfloat, hwacha, ibex, icenet, iocell, nvdla, rocket-dsp-utils, rocketConfig, rocketMacros, rocketchip, sha3, sifive_blocks, sifive_cache, sodor, tapeout, testchipip, tracegen
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
make: *** [/home/wpc/NOC/chipyard/common.mk:111: generator_temp] Error 1

i'm not find 'rocketchip_blocks' in chipyard,  which module does it refer to
